DROP TABLE IF EXISTS Comments;
CREATE TABLE IF NOT EXISTS Comments (
    commentId INTEGER PRIMARY KEY AUTOINCREMENT,
    posterId INT NOT NULL,
    content TEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(posterId) REFERENCES Users(userId)
);