DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users (
    userId INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    hashpass TEXT NOT NULL,
    rank TINYINT UNSIGNED
);